---
title: "My Lab 5"
author: "Skyler Moomey"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1
```{r}
getwd()
```

## Task 2

### Binomial Simulation
```{r}
#Dr. Stewart's sampling function
## sampling function
# iter = iterations, n=sample size
# set default values
mybin=function(iter=100,n=10, p=0.5){ 
  # make a matrix to hold the samples
  #initially filled with NA's
  sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
  #Make a vector to hold the number of successes in each trial
  succ=c()
  for( i in 1:iter){
    #Fill each column with a new sample
    sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))
    #Calculate a statistic from the sample (this case it is the sum)
    succ[i]=sum(sam.mat[,i])
  }
  #Make a table of successes
  succ.tab=table(factor(succ,levels=0:n))
  #Make a barplot of the proportions
  barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial simulation", xlab="Number of successes")
  succ.tab/iter
}
mybin(iter=10000, p=0.7)
```


### Verification

```{r}
#verify values for table with 10000 iterations
dbinom(x=0, size=10, prob=0.7)
dbinom(x=1, size=10, prob=0.7)
dbinom(x=2, size=10, prob=0.7)
dbinom(x=3, size=10, prob=0.7)
dbinom(x=4, size=10, prob=0.7)
dbinom(x=5, size=10, prob=0.7)
dbinom(x=6, size=10, prob=0.7)
dbinom(x=7, size=10, prob=0.7)
dbinom(x=8, size=10, prob=0.7)
dbinom(x=9, size=10, prob=0.7)
dbinom(x=10, size=10, prob=0.7)
```

All of the values in the relative frequency histogram for the Binomial simulation with $10,000$ iterations are approximately their true values.

